version: '3.5'

services:
    nginx:
      image: jwilder/nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx/vhost/:/etc/nginx/vhost.d:ro
        - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
        - ./static/:/code/static/
        - ./media/:/code/media/


  
    postgres:
        container_name: postgres
        image: postgres:12.1
        env_file: 
          - .env
        volumes:
          - ./.postgresdb/:/var/lib/postgresql/data
        ports:
          - "${POSTGRES_PORT}:5432"
        restart: on-failure
 
    web:
        build: .
        restart: "always"
        ports:
        - "8000:8000"
        volumes:
        - .:/code/
        - ./static/:/code/static/
        - ./media/:/code/media/
        depends_on:
            - "postgres"
        environment: 
        - VIRTUAL_HOST=localhost, 34.89.165.165
        - VIRTUAL_PORT=8000
